# Generated by Django 4.0.4 on 2022-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=250)),
            ],
        ),
    ]
